dist: trusty
sudo: required
services:
  - docker

env:
  matrix:
  - TEST_TARGET: kibana

before_install:
  - sudo apt-get remove docker docker-engine
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker version
  - docker info

script:
  - make $TEST_TARGET

notifications:
  slack:
    secure: hTpPIrBwDN0YpUV0bfYtqyzPLw7yv9/PPfd4uijmG/m0L+CkvnUp/52VD5n5EEectl+/kwxduAmm86V0BGa3CL48YVuyHmz5oGPSA0+ugTsrDikQqBk0ZVXjmtlrT5/V3mBs9TzI1FD76WQXZBxx2KkedEJ0ECu6cfse0SMM0M3vgsdC4mHl0OoGUpeqwu+nOtENgFP0hjH18GdFdTksEY8S7FKJU8sY4842Udlgy5dhlPuWRXhtohoFnKVMcX5nJ56M6FrhojOkA52de2RmxSaLtUiQnPXW1z4QynaBLYTTHuDKXWZ5sN/7FnayWNCQwwLi/xXQqQopSkYMkD1JYFwXxiKkfnKFODaiViTilFHsiLmLkivqaz5aJuwxMj5QxQy0xyK50L00c1FLGQopipNLFrO+NNQSCHte2evdolEfZ5iOoy+rcvEejlDuv3eaTOEzaEywk1S/VtBs/XfDBFF0Kpz3GqFzxvS3Ye4T/FA0TpQr+FYr6ghTwVSuM59A/giQM7HtqYgjKSLaH4GN+ZELyHeFLiRIVYjiS1nCYf5F65D1ooF3bVFNt4vNQBm+Z8FGJPqEdGZoXcIOKatfTk5f65rL3nfk+haxEJ+OAEAtswmBzS9L/XqP96bWhQ6wPUdW3XKTdWCAvacpA5UaeduLo5RoUlt0GHkpR6vV2is=
